// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfrpefvailtxhxagxeba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmcnBlZnZhaWx0eGh4YWd4ZWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjQyNjYsImV4cCI6MjA2NzE0MDI2Nn0.QFZoGSrKB2xacYfX9mTHjuly7gBhqi6QxlEtV4CW_eU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});